apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd
          commance: ["/bin/bash", "-c"]# opvveride the default commande
          args: ["sleep 5; exit 1"] #sleep for 30 secs then exit with an error
  strategy:
    type: Recreate
