apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-volume
    method: fromcode
    another: label  
  name: nginx-volume
spec:
  containers:
    - image: nginx
      name: nginx-volume
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
